version: '2.3'

services:
  db:
    container_name: ejemplo_container_db
    image: mariadb
    env_file: ./.env
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - '${DATABASE_PORT}:3306'
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  php:
    container_name: ejemplo_container_php
    image: php:7.1
    env_file: ./.env
    build:
      context: ./.docker
      dockerfile: Dockerfile
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      TZ: America/Mexico_City
      DB_HOST: ${DATABASE_HOST}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      DB_DRIVER: mysql
    volumes:
      - .:${SERVER_ROOT}:cached
    depends_on:
      db:
        condition: service_healthy
    labels:
      - 'traefik.backend=php'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${HOST_NAME}'

################ Extra toolkit images.
  mailhog:
    container_name: ejemplo_container_mailhog
    image: mailhog/mailhog
    env_file: ./.env
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${HOST_NAME}'

  traefik:
    container_name: ejemplo_container_traefik
    image: traefik
    env_file: ./.env
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '${HOST_PORT}:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mysqldata:
    driver: "local"
