version: '3'

services:
  db:
    container_name: ejemplo_container_db
    image: mariadb
    volumes:
      - ./.docker/mysqlconf:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
    ports:
      - "8106:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project_db
      MYSQL_USER: project_user
      MYSQL_PASSWORD: root

  php:
    container_name: ejemplo_container_php
    depends_on:
      - db
      - mailhog
    image: php:7.1
    build:
      context: ./.docker
      dockerfile: Dockerfile
    links:
      - db
      - mailhog
    volumes:
      - .:/var/www/html
      - ./.docker/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./.docker/virtualhost-php.conf:/etc/apache2/sites-available/001-virtualhost-php.conf
      - ./logs/error.log:/var/www/error.log
      - ./logs/access.log:/var/www/access.log
    ports:
      - "8180:80"
      - "8143:443"
    environment:
      DB_HOST: db:3306
      DB_USER: root
      DB_PASSWORD: root

################ Extra toolkit images.
  mailhog:
    container_name: ejemplo_container_mailhog
    image: mailhog/mailhog
    ports:
      - 8125:8025
      - 8126:1025

volumes:
  db_data:
